spring.application.name=trivio

# Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=trivio
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

## JWT
#app.security.jwt.secret=change-me-super-secret-256bit-key-change-me
#app.security.jwt.expiration-seconds=86400
#
## CORS
#spring.web.cors.allowed-origins=http://localhost:5173
#spring.web.cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
#spring.web.cors.allowed-headers=Content-Type,Authorization
#spring.web.cors.allow-credentials=true

# Logging
logging.level.org.springframework.security=DEBUG