spring.application.name=trivio

# Oracle
spring.datasource.url=jdbc:oracle:thin:@${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

## JWT
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.expiration-seconds=86400

# Logging
logging.level.org.springframework.security=DEBUG

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
